defaults:
  - _self_
  - base_config
experiment:
  name: "tdm_training"
env:
  name: "AntMaze_UMaze-v4"
  device: "cpu"
  obs:
    height: 128
    width: 128
    raw_height: 480
    raw_width: 480
    dim: 3
    normalize: True
    standardization_stats_init_iter: 0
    standardize: False
  goal:
    dim: 512
replay_buffer:
  max_size: 100000
train:
  num_episodes: 2
  initial_max_planning_horizon: 15
  planning_horizon_annealing_strategy: "linear"
  planning_horizon_annealing_cycles: 1
  planning_horizon_annealing_ratio: 0.75
  planning_horizon_annealing_steps: 50
  max_frames_per_traj: 128
  init_random_frames: 0
  frames_per_batch: 1
  reset_at_each_iter: False
  collector_device: "cpu"
  storing_device: "cpu"
  updates_per_step: 20
models:
  device: "cuda"
  policy:
    fc1_out_features: 128