defaults:
  - _self_
  - base_config
experiment:
  name: "tdm_training"
env:
  name: "AntMaze_UMaze-v4"
  obs:
    height: 128
    width: 128
    normalize: True
    standardization_stats_init_iter: 0
    standardize: False
replay_buffer:
  max_size: 100000
train:
  num_episodes: 2
  max_planning_horizon: 15
  max_frames_per_traj: 128
  init_random_frames: 0
  frames_per_batch: 1
  reset_at_each_iter: False
  collector_device: "cpu"
  storing_device: "cpu"
  updates_per_step: 20