defaults:
  - _self_
  - base_config
experiment:
  name: "tdm_training"
env:
  name: "AntMaze_UMaze-v4"
  device: "cpu"
  obs:
    height: 128
    width: 128
    raw_height: 480
    raw_width: 480
    dim: 3
    normalize: True
    standardization_stats_init_iter: 0
    standardize: False
  goal:
    latent_dim: 256
    norm_type: "l1"
replay_buffer:
  max_size: 100000
train:
  num_episodes: 2
  initial_max_planning_horizon: 15
  planning_horizon_annealing_strategy: "linear"
  planning_horizon_annealing_cycles: 1
  planning_horizon_annealing_ratio: 0.5
  planning_horizon_annealing_steps: 50
  max_frames_per_traj: 256
  init_random_frames: 0
  frames_per_batch: 2048
  reset_at_each_iter: False
  collector_device: "cpu"
  storing_device: "cpu"
  updates_per_step: 20
models:
  device: "cuda"
  encoder_decoder:
    name: "vae_best_model_antmaze_umaze-v4"
    version: "1.0.0"
    download_path: "models/encoder_decoder/"
    encoder:
      hidden_dims: [16, 32, 64, 128]
      hidden_activation: "leaky_relu"
      leaky_relu_neg_slope: 0.2
      hidden_kernels: [4, 4, 4, 4]
      hidden_strides: [2, 2, 2, 2]
      hidden_paddings: [1, 1, 1, 1]
      use_batch_norm: True
    decoder:
      hidden_dims: [64, 32, 16]
      hidden_activation: "relu"
      hidden_kernels: [4, 4, 4]
      hidden_strides: [2, 2, 2]
      hidden_paddings: [1, 1, 1]
      output_kernel: 4
      output_stride: 2
      output_padding: 1
      use_batch_norm: True
  policy:
    fc1_out_features: 128