defaults:
  - _self_
  - base_config
experiment:
  name: "vae"
env:
  name: "AntMaze_UMaze-v4"
  train_frames_per_batch: 512
  train_max_frames_per_traj: 4096
  train_reset_at_each_iter: False
  eval_frames: 128
  obs:
    width: 128
    height: 128
    normalize: True
    standardize: False
    standardization_stats_init_iter: 0
replay_buffer:
  max_size: 4096
alg:
  max_train_steps: 32768
  train_steps_per_iter: 64
  train_batch_size: 64
  kl_divergence_beta: 5
  kl_divergence_annealing_strategy: "cyclic_linear"
  kl_divergence_annealing_cycles: 4
  kl_divergence_annealing_ratio: 0.5
  reconstruction_loss: "bce"
model:
  optimizer:
    name: "adam"
    lr: 0.001
  params:
    input_dim: 3
    encoder_hidden_dims: [16, 32, 64, 128, 128, 128]
    encoder_kernels: [1, 5, 5, 4, 3, 4]
    encoder_strides: [1, 1, 1, 2, 2, 1]
    encoder_paddings: [0, 0, 0, 0, 0, 0]
    encoder_last_layer_fc: True
    encoder_last_spatial_dim: 26
    latent_dim: 64
    decoder_hidden_dims: [128, 128, 128, 64, 32, 16]
    decoder_kernels: [-1, 4, 3, 4, 5, 5]
    decoder_strides: [-1, 1, 2, 2, 1, 1]
    decoder_paddings: [-1, 0, 0, 0, 0, 0]
logging:
  log_steps_interval: 100
  train_plot_samples: 6
