defaults:
  - _self_
  - base_config
  - env: antmaze_umaze
experiment:
  name: "vae_dataset_generation"
env:
  max_frames_per_traj: 128
  frames_per_batch: 2048 # Adjust based on RAM limitation, must be >= logging.images_grid_rows * logging.images_grid_columns
  reset_at_each_iter: False
dataset:
  name: vae_dataset_${env.name}_${dataset.size}
  save_dir: "datasets/"
  size: 65536
logging:
  video_log_steps_interval: 8192
  video_max_frames: 128
  video_rollouts: 5
  images_log_steps_interval: 4096
  images_grid_rows: 6
  images_grid_columns: 6
