defaults:
  - _self_
  - base_config
experiment:
  name: "vae_dataset_generation"
env:
  name: "AntMaze_UMaze-v4"
  total_frames: 65536
  max_frames_per_traj: 128
  frames_per_batch: 2048 # Adjust based on RAM limitation
  reset_at_each_iter: False
  obs:
    raw_height: 480
    raw_width: 480
dataset:
  name: vae_dataset_${env.name}_${env.total_frames}
  save_dir: "datasets/"
logging:
  video_log_steps_interval: 32768
  video_max_steps: 128
  video_rollouts: 5
